### ISSUE TITLE
Add manual for working with git

### ISSUE THREAD

**Issue by arybin93** [nnstu-appmath/kb#5]
Добавить инструкцию для работы c git репозиториями в рамках курса
1. Creating issue
2. Generating SSH if not exists (Согласовать с @PeshinaA, чтобы не повторяться, добавить ссылку на материал по SSH)
3. Git clone repo
4. Create branch
5. Git commit
6. Git Push
7. Create Pull Request (Add reviewers)

Посмотреть, что уже подготовила Юлия Бутусова и избежать дублирования информации (Добавить ссылки на материал).

**Comment by IshuDivan** [comment]
Понял, спасибо.

суббота, 10 сентября 2022 г. пользователь Artem Rybin <
***@***.***> написал:

**Comment by arybin93** [comment]
@IshuDivan Иван, видимо письмо на которое был ответ это нотификация с гитхаба, если есть какие-то вопросы по этой задаче пишите

**Comment by 1Serhio** [comment]
Файл Git_introduction.md, содержащий вводную информацию о Git, добавлен в папку Git ветки 5_git_introduction репозитория kb. Создан PR #38.
